  spring:
    datasource:
      url: jdbc:h2:mem:sdw:2023
      username: sdw2023
      password:
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: create # validate / uptade / create / create-drop
      properties:
        hibernate:
          format_sql: true
   h2:
     console:
       enabled: true
       path: /h2-console
       settings:
         trace: false
         web-allow-others: false